version: '3.8'
services:
  # API Gateway
  gateway:
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - bute-ai-network
    volumes:
       - ./traefik.yml:/etc/traefik/traefik.yml
       - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.swagger.rule=PathPrefix(`/api`) && Path(`/swagger`)"
      - "traefik.http.routers.swagger.middlewares=strip-prefix"
      - "traefik.http.middlewares.strip-prefix.stripprefixregex.regex=/api/(.*)"
      - "traefik.http.middlewares.strip-prefix.stripprefixregex.replacement=/$$1"

  # Core - Service
  core:
    build:
      context: ./bute-ai-core
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core.rule=PathPrefix(`/api/core`)"
      - "traefik.http.services.core.loadbalancer.server.port=8000"
      - "traefik.http.services.core.loadbalancer.server.scheme=http"
      - "traefik.http.services.core.loadbalancer.sticky=true"
      - "traefik.http.services.core.loadbalancer.sticky.cookie.name=core_cookie"
    networks:
      - bute-ai-network
    
  auth:
    build:
      context: ./bute-ai-auth
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.services.auth.loadbalancer.server.scheme=http"
      - "traefik.http.services.auth.loadbalancer.sticky=true"
      - "traefik.http.services.auth.loadbalancer.sticky.cookie.name=auth_cookie"
    networks:
      - bute-ai-network

  # Transfer - Service
  transfer:
    build:
      context: ./bute-ai-transfer
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfer.rule=PathPrefix(`/api/transfer`)"
      - "traefik.http.services.transfer.loadbalancer.server.port=8000"
      - "traefik.http.services.transfer.loadbalancer.server.scheme=http"
      - "traefik.http.services.transfer.loadbalancer.sticky=true"
      - "traefik.http.services.transfer.loadbalancer.sticky.cookie.name=transfer_cookie"
    networks:
      - bute-ai-network

  # WhoAmI
  whoami:
    image: traefik/whoami
    ports:
      - "81:80"
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    networks:
      - bute-ai-network

volumes:
  gateway-volume:

networks:
  bute-ai-network:
