name: Copy File to Server

on:
  push:
    branches:
      - Main
  pull_request:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy file to server
        run: |
          scp -i ${{ secrets.PATH_TO_SSH_KEY }} -v ${{ secrets.LOCAL_FILE_PATH }} ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.REMOTE_FILE_PATH }}
