name: Copy File to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy file to server
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          scp -i ${{ secrets.PATH_TO_SSH_KEY }} ${{ secrets.LOCAL_FILE_PATH }} ${{ USERNAME }}@${{ SERVER_IP }}:${{ REMOTE_FILE_PATH }}
